export const languageToFileEnding = {
  "JavaScript": ".js",
  "Haskell": ".hs",
  "C++": ".cpp",
  "C": ".c",
  "Go": ".go",
  "TypeScript": ".ts",
  "Clojure": ".clj",
  "Dart": ".dart",
  "Python": ".py",
  "Swift": ".swift",
  "Ruby": ".rb",
  "Java": ".java",
  "PHP": ".php",
  "Common Lisp": ".lisp",
  "D": ".d",
  "Elixir": ".ex",
  "Free Pascal": ".pas",
  "Fortran": ".for",
  "F#": ".fs",
  "C#": ".cs",
  "Groovy": ".groovy",
  "Julia": ".jl",
  "Lua": ".lua",
  "Nim": ".nim",
  "Objective-C": ".m",
  "OCaml": ".ml",
  "GNU Octave": ".m",
  "Perl": ".pl",
  "Kotlin": ".kt",
  "Erlang": ".erl",
  "Rust": ".rc",
  "Scala": ".scala",
  "Smalltalk": ".st",
  "Tcl": ".tcl",
  "Visual Basic": ".vb",
  "MySQL": ".sql",
};

export const parsedLinksPath = "temp/alreadyParsedLinks";
